-- ICAO phonetic alphabet, added to dictionary_terms -- 2026-08-28
--
-- RC, real device, angry and correct: "Where is the phonetic alphabet in
-- our Aviation dictionary? I type in Juliet... nothing shows up... that
-- is of primary importance to aviators." Confirmed: genuinely zero rows
-- for any phonetic-alphabet content across all 9,813 existing
-- dictionary_terms (and zero in pcg_terms too) -- not a search bug, the
-- content itself was never authored.
--
-- 26 individual letter entries (JULIET, ALFA, BRAVO, ...) so searching
-- any one word finds it directly, category='informal' (a plain term +
-- definition, same shape as this table's existing slang entries) --
-- plus one master "PHONETIC ALPHABET" reference entry using
-- category='mnemonic' (the SAME breakdown-array shape this table
-- already uses for other letter-by-letter mnemonics like "6 T's"/"MARC")
-- so it can hold the full A-Z list in one place, per RC's own ask:
-- "if you search the term phonetic alphabet that explanation window
-- should... include the entire list of the letter and its phonetic
-- word next to it through the entire alphabet."
--
-- Source: ICAO Annex 10 / FAA AIM 4-2-6 -- standardized, publicly
-- documented, unambiguous; authored directly, no LLM pass needed.
--
-- This file documents the insert for history; the real data was
-- inserted live via a one-off script (not saved) using this same
-- content. Re-running this file is safe -- ON CONFLICT DO NOTHING on
-- the table's own unique slug constraint.

insert into public.dictionary_terms (term, slug, letter, category, senses, source, mnemonic_group, see_also_slug) values
('ALFA', 'phonetic-alfa', 'A', 'informal', '[{"usage": null, "definition": "The ICAO/FAA phonetic alphabet word for the letter A, used to spell out letters clearly over the radio (e.g. tail number, ATIS code, taxiway)."}]', 'ICAO phonetic alphabet (Annex 10, also published in the FAA''s own AIM 4-2-6)', null, 'mnem-phonetic-alphabet'),
('BRAVO', 'phonetic-bravo', 'B', 'informal', '[{"usage": null, "definition": "The ICAO/FAA phonetic alphabet word for the letter B, used to spell out letters clearly over the radio (e.g. tail number, ATIS code, taxiway)."}]', 'ICAO phonetic alphabet (Annex 10, also published in the FAA''s own AIM 4-2-6)', null, 'mnem-phonetic-alphabet'),
('CHARLIE', 'phonetic-charlie', 'C', 'informal', '[{"usage": null, "definition": "The ICAO/FAA phonetic alphabet word for the letter C, used to spell out letters clearly over the radio (e.g. tail number, ATIS code, taxiway)."}]', 'ICAO phonetic alphabet (Annex 10, also published in the FAA''s own AIM 4-2-6)', null, 'mnem-phonetic-alphabet'),
('DELTA', 'phonetic-delta', 'D', 'informal', '[{"usage": null, "definition": "The ICAO/FAA phonetic alphabet word for the letter D, used to spell out letters clearly over the radio (e.g. tail number, ATIS code, taxiway)."}]', 'ICAO phonetic alphabet (Annex 10, also published in the FAA''s own AIM 4-2-6)', null, 'mnem-phonetic-alphabet'),
('ECHO', 'phonetic-echo', 'E', 'informal', '[{"usage": null, "definition": "The ICAO/FAA phonetic alphabet word for the letter E, used to spell out letters clearly over the radio (e.g. tail number, ATIS code, taxiway)."}]', 'ICAO phonetic alphabet (Annex 10, also published in the FAA''s own AIM 4-2-6)', null, 'mnem-phonetic-alphabet'),
('FOXTROT', 'phonetic-foxtrot', 'F', 'informal', '[{"usage": null, "definition": "The ICAO/FAA phonetic alphabet word for the letter F, used to spell out letters clearly over the radio (e.g. tail number, ATIS code, taxiway)."}]', 'ICAO phonetic alphabet (Annex 10, also published in the FAA''s own AIM 4-2-6)', null, 'mnem-phonetic-alphabet'),
('GOLF', 'phonetic-golf', 'G', 'informal', '[{"usage": null, "definition": "The ICAO/FAA phonetic alphabet word for the letter G, used to spell out letters clearly over the radio (e.g. tail number, ATIS code, taxiway)."}]', 'ICAO phonetic alphabet (Annex 10, also published in the FAA''s own AIM 4-2-6)', null, 'mnem-phonetic-alphabet'),
('HOTEL', 'phonetic-hotel', 'H', 'informal', '[{"usage": null, "definition": "The ICAO/FAA phonetic alphabet word for the letter H, used to spell out letters clearly over the radio (e.g. tail number, ATIS code, taxiway)."}]', 'ICAO phonetic alphabet (Annex 10, also published in the FAA''s own AIM 4-2-6)', null, 'mnem-phonetic-alphabet'),
('INDIA', 'phonetic-india', 'I', 'informal', '[{"usage": null, "definition": "The ICAO/FAA phonetic alphabet word for the letter I, used to spell out letters clearly over the radio (e.g. tail number, ATIS code, taxiway)."}]', 'ICAO phonetic alphabet (Annex 10, also published in the FAA''s own AIM 4-2-6)', null, 'mnem-phonetic-alphabet'),
('JULIET', 'phonetic-juliet', 'J', 'informal', '[{"usage": null, "definition": "The ICAO/FAA phonetic alphabet word for the letter J, used to spell out letters clearly over the radio (e.g. tail number, ATIS code, taxiway). Officially spelled \"Juliett\" (two Ts) by ICAO, though \"Juliet\" is the common spelling."}]', 'ICAO phonetic alphabet (Annex 10, also published in the FAA''s own AIM 4-2-6)', null, 'mnem-phonetic-alphabet'),
('KILO', 'phonetic-kilo', 'K', 'informal', '[{"usage": null, "definition": "The ICAO/FAA phonetic alphabet word for the letter K, used to spell out letters clearly over the radio (e.g. tail number, ATIS code, taxiway)."}]', 'ICAO phonetic alphabet (Annex 10, also published in the FAA''s own AIM 4-2-6)', null, 'mnem-phonetic-alphabet'),
('LIMA', 'phonetic-lima', 'L', 'informal', '[{"usage": null, "definition": "The ICAO/FAA phonetic alphabet word for the letter L, used to spell out letters clearly over the radio (e.g. tail number, ATIS code, taxiway)."}]', 'ICAO phonetic alphabet (Annex 10, also published in the FAA''s own AIM 4-2-6)', null, 'mnem-phonetic-alphabet'),
('MIKE', 'phonetic-mike', 'M', 'informal', '[{"usage": null, "definition": "The ICAO/FAA phonetic alphabet word for the letter M, used to spell out letters clearly over the radio (e.g. tail number, ATIS code, taxiway)."}]', 'ICAO phonetic alphabet (Annex 10, also published in the FAA''s own AIM 4-2-6)', null, 'mnem-phonetic-alphabet'),
('NOVEMBER', 'phonetic-november', 'N', 'informal', '[{"usage": null, "definition": "The ICAO/FAA phonetic alphabet word for the letter N -- also the prefix letter for every US-registered aircraft tail number (\"N12345\")."}]', 'ICAO phonetic alphabet (Annex 10, also published in the FAA''s own AIM 4-2-6)', null, 'mnem-phonetic-alphabet'),
('OSCAR', 'phonetic-oscar', 'O', 'informal', '[{"usage": null, "definition": "The ICAO/FAA phonetic alphabet word for the letter O, used to spell out letters clearly over the radio (e.g. tail number, ATIS code, taxiway)."}]', 'ICAO phonetic alphabet (Annex 10, also published in the FAA''s own AIM 4-2-6)', null, 'mnem-phonetic-alphabet'),
('PAPA', 'phonetic-papa', 'P', 'informal', '[{"usage": null, "definition": "The ICAO/FAA phonetic alphabet word for the letter P, used to spell out letters clearly over the radio (e.g. tail number, ATIS code, taxiway)."}]', 'ICAO phonetic alphabet (Annex 10, also published in the FAA''s own AIM 4-2-6)', null, 'mnem-phonetic-alphabet'),
('QUEBEC', 'phonetic-quebec', 'Q', 'informal', '[{"usage": null, "definition": "The ICAO/FAA phonetic alphabet word for the letter Q, used to spell out letters clearly over the radio (e.g. tail number, ATIS code, taxiway)."}]', 'ICAO phonetic alphabet (Annex 10, also published in the FAA''s own AIM 4-2-6)', null, 'mnem-phonetic-alphabet'),
('ROMEO', 'phonetic-romeo', 'R', 'informal', '[{"usage": null, "definition": "The ICAO/FAA phonetic alphabet word for the letter R, used to spell out letters clearly over the radio (e.g. tail number, ATIS code, taxiway)."}]', 'ICAO phonetic alphabet (Annex 10, also published in the FAA''s own AIM 4-2-6)', null, 'mnem-phonetic-alphabet'),
('SIERRA', 'phonetic-sierra', 'S', 'informal', '[{"usage": null, "definition": "The ICAO/FAA phonetic alphabet word for the letter S, used to spell out letters clearly over the radio (e.g. tail number, ATIS code, taxiway)."}]', 'ICAO phonetic alphabet (Annex 10, also published in the FAA''s own AIM 4-2-6)', null, 'mnem-phonetic-alphabet'),
('TANGO', 'phonetic-tango', 'T', 'informal', '[{"usage": null, "definition": "The ICAO/FAA phonetic alphabet word for the letter T, used to spell out letters clearly over the radio (e.g. tail number, ATIS code, taxiway)."}]', 'ICAO phonetic alphabet (Annex 10, also published in the FAA''s own AIM 4-2-6)', null, 'mnem-phonetic-alphabet'),
('UNIFORM', 'phonetic-uniform', 'U', 'informal', '[{"usage": null, "definition": "The ICAO/FAA phonetic alphabet word for the letter U, used to spell out letters clearly over the radio (e.g. tail number, ATIS code, taxiway)."}]', 'ICAO phonetic alphabet (Annex 10, also published in the FAA''s own AIM 4-2-6)', null, 'mnem-phonetic-alphabet'),
('VICTOR', 'phonetic-victor', 'V', 'informal', '[{"usage": null, "definition": "The ICAO/FAA phonetic alphabet word for the letter V, used to spell out letters clearly over the radio (e.g. tail number, ATIS code, taxiway)."}]', 'ICAO phonetic alphabet (Annex 10, also published in the FAA''s own AIM 4-2-6)', null, 'mnem-phonetic-alphabet'),
('WHISKEY', 'phonetic-whiskey', 'W', 'informal', '[{"usage": null, "definition": "The ICAO/FAA phonetic alphabet word for the letter W, used to spell out letters clearly over the radio (e.g. tail number, ATIS code, taxiway)."}]', 'ICAO phonetic alphabet (Annex 10, also published in the FAA''s own AIM 4-2-6)', null, 'mnem-phonetic-alphabet'),
('X-RAY', 'phonetic-x-ray', 'X', 'informal', '[{"usage": null, "definition": "The ICAO/FAA phonetic alphabet word for the letter X, used to spell out letters clearly over the radio (e.g. tail number, ATIS code, taxiway)."}]', 'ICAO phonetic alphabet (Annex 10, also published in the FAA''s own AIM 4-2-6)', null, 'mnem-phonetic-alphabet'),
('YANKEE', 'phonetic-yankee', 'Y', 'informal', '[{"usage": null, "definition": "The ICAO/FAA phonetic alphabet word for the letter Y, used to spell out letters clearly over the radio (e.g. tail number, ATIS code, taxiway)."}]', 'ICAO phonetic alphabet (Annex 10, also published in the FAA''s own AIM 4-2-6)', null, 'mnem-phonetic-alphabet'),
('ZULU', 'phonetic-zulu', 'Z', 'informal', '[{"usage": null, "definition": "The ICAO/FAA phonetic alphabet word for the letter Z, used to spell out letters clearly over the radio (e.g. tail number, ATIS code, taxiway). Also the aviation name for UTC/Greenwich time (\"1400 Zulu\")."}]', 'ICAO phonetic alphabet (Annex 10, also published in the FAA''s own AIM 4-2-6)', null, 'mnem-phonetic-alphabet'),
('PHONETIC ALPHABET', 'mnem-phonetic-alphabet', 'P', 'mnemonic',
 '[{"usage": null, "definition": "The ICAO phonetic alphabet (also called the NATO phonetic alphabet) assigns a standard word to each letter so it''s unambiguous over a noisy radio -- e.g. spelling a tail number or reading back a clearance letter-by-letter. Published in FAA AIM 4-2-6 and ICAO Annex 10.", "breakdown": [{"letter":"A","concept":"Alfa","detail":""},{"letter":"B","concept":"Bravo","detail":""},{"letter":"C","concept":"Charlie","detail":""},{"letter":"D","concept":"Delta","detail":""},{"letter":"E","concept":"Echo","detail":""},{"letter":"F","concept":"Foxtrot","detail":""},{"letter":"G","concept":"Golf","detail":""},{"letter":"H","concept":"Hotel","detail":""},{"letter":"I","concept":"India","detail":""},{"letter":"J","concept":"Juliet","detail":""},{"letter":"K","concept":"Kilo","detail":""},{"letter":"L","concept":"Lima","detail":""},{"letter":"M","concept":"Mike","detail":""},{"letter":"N","concept":"November","detail":""},{"letter":"O","concept":"Oscar","detail":""},{"letter":"P","concept":"Papa","detail":""},{"letter":"Q","concept":"Quebec","detail":""},{"letter":"R","concept":"Romeo","detail":""},{"letter":"S","concept":"Sierra","detail":""},{"letter":"T","concept":"Tango","detail":""},{"letter":"U","concept":"Uniform","detail":""},{"letter":"V","concept":"Victor","detail":""},{"letter":"W","concept":"Whiskey","detail":""},{"letter":"X","concept":"X-ray","detail":""},{"letter":"Y","concept":"Yankee","detail":""},{"letter":"Z","concept":"Zulu","detail":""}]}]',
 'ICAO phonetic alphabet (Annex 10, also published in the FAA''s own AIM 4-2-6)', 'Communications', null)
on conflict (slug) do nothing;
