#!/bin/bash
# Local iOS build with Xcode 26.3 (Swift 6.2.4) -- the toolchain Expo SDK 56 / RN 0.85 requires.
#
# PREREQUISITE, ONE TIME, NEEDS RC'S PASSWORD (Claude cannot run sudo):
#   sudo env DEVELOPER_DIR=/Applications/Xcode-26.3.app/Contents/Developer xcodebuild -license accept
#
# Deliberately uses DEVELOPER_DIR instead of `xcode-select -s` so the global
# toolchain stays on Xcode 16.4 -- switching it system-wide has broken python3 here before.
set -euo pipefail

export DEVELOPER_DIR=/Applications/Xcode-26.3.app/Contents/Developer
PROJ_DIR="$(cd "$(dirname "$0")/.." && pwd)"
SIM_UDID="${SIM_UDID:-DBE4D72A-390A-472E-AD4C-FCAEA0B8C84E}"   # iPhone 13 mini, RC's device class
DERIVED="$PROJ_DIR/build/DerivedData"
# Debug is the default (fast, hot-reload via Metro). Release embeds the JS
# bundle and drops expo-dev-client's floating gear overlay -- which sits over
# the top-right of EVERY screen and silently eats taps there, so a UI sweep
# must use Release or it will mis-click its way to false findings.
CONFIG="${CONFIG:-Debug}"
echo "==> Configuration: $CONFIG"

# A local Release build otherwise dies in "Bundle React Native code and images":
#   error: Auth token is required for this request. Please run `sentry-cli login`
# @sentry/react-native's Xcode phase tries to upload source maps and treats a
# missing token as fatal. EAS injects that token, so production builds are fine
# -- but it makes a local Release build impossible, which is exactly the
# configuration you want when testing what users actually run.
#
# Source maps only matter for a build whose crashes get symbolicated in Sentry.
# A simulator build is never that, so opt out rather than handing sentry-cli a
# real credential just to compile.
export SENTRY_DISABLE_AUTO_UPLOAD=true

echo "==> Xcode: $(xcodebuild -version | head -1)"
echo "==> Swift: $("$DEVELOPER_DIR/Toolchains/XcodeDefault.xctoolchain/usr/bin/swift" --version | head -1)"

cd "$PROJ_DIR/ios"
# Ask the WORKSPACE explicitly. With both a .xcodeproj and a .xcworkspace in
# this directory, a bare `xcodebuild -list` describes the PROJECT, so the JSON
# has a "project" key and not "workspace" -- the first version indexed
# ["workspace"] and died on a KeyError before building anything.
WS="$(ls -d *.xcworkspace | head -1)"
# Pick the APP scheme by name, never schemes[0]. CocoaPods puts ~150 schemes in
# this workspace and the first alphabetically is "EXApplication", an Expo pod --
# building that got as far as "Available destinations: macOS Catalyst only"
# before failing, which reads like a simulator problem and is not one.
APP_SCHEME="${APP_SCHEME:-${WS%.xcworkspace}}"
SCHEME="$(xcodebuild -list -json -workspace "$WS" 2>/dev/null \
  | APP_SCHEME="$APP_SCHEME" python3 -c 'import json, os, sys
d = json.load(sys.stdin)
schemes = (d.get("workspace") or d["project"])["schemes"]
want = os.environ["APP_SCHEME"]
if want not in schemes:
    sys.exit(f"scheme {want!r} not in the workspace; have {schemes[:5]}...")
print(want)')"
echo "==> Scheme: $SCHEME"

# `ios/` is gitignored and regenerated by `expo prebuild`, so the fix below
# cannot live in project.pbxproj. Idempotent, and re-applied every build so it
# self-heals after a prebuild instead of silently reverting. See the script's
# own docstring for the failure it prevents.
python3 "$PROJ_DIR/scripts/patch_ios_space_paths.py"

# NOT `xcodebuild ... | tee log | tail -40`. Under `set -o pipefail` a failing
# xcodebuild kills the script at the pipe, before it can say what happened --
# and `tail -40` throws away the "** BUILD SUCCEEDED/FAILED **" line anyway. The
# first run this way ended with no verdict in the log at all, left an EMPTY
# FlyRegs.app behind, and I briefly read "the path exists" as "it built".
# Capture the status, then always report it.
mkdir -p "$PROJ_DIR/build"
LOG="$PROJ_DIR/build/xcodebuild.log"
set +e
xcodebuild \
  -workspace "$WS" \
  -scheme "$SCHEME" \
  -configuration "$CONFIG" \
  -sdk iphonesimulator \
  -destination "id=$SIM_UDID" \
  -derivedDataPath "$DERIVED" \
  build > "$LOG" 2>&1
STATUS=$?
set -e
grep -aE "(^| )error: " "$LOG" | head -20 || true
if [ "$STATUS" -ne 0 ] || ! grep -qa '^\*\* BUILD SUCCEEDED \*\*' "$LOG"; then
  echo "==> BUILD FAILED (exit $STATUS). Full log: $LOG"
  exit 1
fi
echo "==> BUILD SUCCEEDED"

APP="$(find "$DERIVED/Build/Products" -name '*.app' -maxdepth 3 | head -1)"
# An interrupted build leaves the .app DIRECTORY with nothing in it, so check
# for the thing simctl actually needs rather than for the path.
if [ -z "$APP" ] || [ ! -f "$APP/Info.plist" ]; then
  echo "==> No usable app bundle (missing Info.plist) at: ${APP:-<none>}"
  exit 1
fi
echo "==> Built: $APP"

# expo-constants ships a build phase that is supposed to write app.config into
# EXConstants.bundle. It silently no-ops here (get-app-config-ios.sh early-exits
# unless `basename $PROJECT_DIR` == "Pods", and exits 0 when it does not), so a
# RELEASE build launches and then dies instantly with:
#   Error: expo-linking needs access to the expo-constants manifest
# DEBUG never notices, because expo-constants reads the manifest from the Metro
# dev server at runtime instead of from the bundle.
#
# Generating it here rather than fighting the pod phase: the generator itself
# works fine when invoked directly, and a Release build that cannot launch is
# useless for testing what users actually run.
CONSTANTS_BUNDLE="$APP/EXConstants.bundle"
if [ -d "$CONSTANTS_BUNDLE" ] && [ ! -f "$CONSTANTS_BUNDLE/app.config" ]; then
  echo "==> Generating the expo-constants manifest (the pod phase no-ops here)"
  node "$PROJ_DIR/node_modules/expo-constants/scripts/getAppConfig.js" \
    "$PROJ_DIR" "$CONSTANTS_BUNDLE" >/dev/null 2>&1 \
    && echo "==> app.config written" \
    || echo "==> WARNING: could not generate app.config; a Release build will crash at launch"
fi

xcrun simctl boot "$SIM_UDID" 2>/dev/null || true
xcrun simctl install "$SIM_UDID" "$APP"
echo "==> Installed to simulator $SIM_UDID"
echo "==> Now test the AD compliance keyboard at BOTH entry points:"
echo "      src/app/my-aircraft/index.tsx:2439   and   src/app/my-aircraft/[id].tsx:1615"
echo "==> REMINDER: turn OFF Simulator > I/O > Keyboard > Connect Hardware Keyboard,"
echo "    or the software keyboard never appears and the test proves nothing."
