#!/usr/bin/env python3
"""Quote the RN bundle script's command substitutions so a path with spaces works.

This project lives at "/Users/rc/Local Desktop/COWORK/Apps/AC app/ac-app" --
two spaces. The "Bundle React Native code and images" phase that Expo's prebuild
template generates ends with:

    /bin/sh `"$NODE_BINARY" --print "...sentry-xcode.sh"` `"$NODE_BINARY" --print "...react-native-xcode.sh"`

The backticks are UNQUOTED, so the resulting paths word-split at the space and
the build dies with:

    /bin/sh: /Users/rc/Local: No such file or directory
    Command PhaseScriptExecution failed with a nonzero exit code

`ios/` is gitignored and regenerated by `expo prebuild`, so a hand-edit there
does not survive. This script is tracked, is idempotent, and is run by
scripts/build_ios_local.sh before every local build -- so it self-heals after a
prebuild instead of silently reverting.

It touches ONLY the local Xcode project. EAS builds check out to a space-free
path and never hit this, so nothing about the shipped build changes.
"""
import os
import re
import sys

BASE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
# BOTH generated projects. The app's own project comes from `expo prebuild`; the
# Pods project from `pod install`. ios/ is gitignored in its entirety -- including
# ios/Podfile -- so a post_install hook there is NOT durable either, which is why
# every fix lives in this tracked script instead.
PROJECTS = [
    os.path.join(BASE, "ios", "FlyRegs.xcodeproj", "project.pbxproj"),
    os.path.join(BASE, "ios", "Pods", "Pods.xcodeproj", "project.pbxproj"),
]

# The pbxproj stores each script as ONE escaped string, so `"` appears as \" .
#
# Deliberately general: match ANY backtick command substitution, not just
# `"$NODE_BINARY" --print`. Fixing them one at a time meant three builds and
# three separate failures -- the RN bundle phase, then Sentry's debug-symbol
# upload (`${NODE_BINARY:-node} --print ...`), and every one of them is the same
# defect. Any unquoted substitution whose output is a path breaks on a path with
# spaces, so quote them all.
BACKTICK = re.compile(r"`([^`\n]+)`")

# The other shape, from expo-constants:
#     bash -l -c "$PODS_TARGET_SRCROOT/../scripts/get-app-config-ios.sh"
# `bash -c` re-parses the string AFTER the shell expands the variable, so the
# space splits it there too. Single-quote the path: the outer double quotes
# still expand it, the single quotes survive the second parse. Any VAR=value
# prefix must stay outside the quotes to remain an assignment.
# `(?<!')` is load-bearing: without it a SECOND run matches its own output and
# produces ''$VAR...'' , which is broken. This script runs before every build,
# so a non-idempotent rule would corrupt the project on build number two.
BASH_LC = re.compile(r'''(bash -l -c \\")([^"]*?)((?<!')\$[A-Z_]+[^"]*?)(\\")''')


def main():
    total = 0
    for pbx in PROJECTS:
        if not os.path.exists(pbx):
            print(f"  skip (absent): {os.path.relpath(pbx, BASE)}")
            continue
        src = open(pbx, encoding="utf-8").read()
        fixed, a = BACKTICK.subn(lambda m: '\\"$(' + m.group(1) + ')\\"', src)
        fixed, b = BASH_LC.subn(
            lambda m: m.group(1) + m.group(2) + "'" + m.group(3) + "'" + m.group(4), fixed)
        if a + b:
            open(pbx, "w", encoding="utf-8").write(fixed)
        total += a + b
        print(f"  {os.path.relpath(pbx, BASE)}: {a} backtick, {b} bash -l -c")
    if total == 0:
        print("already quoted (or upstream fixed it) -- nothing to do")
    else:
        print(f"quoted {total} unquoted path expansion(s)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
