#!/usr/bin/env python3
"""Quote the RN bundle script's command substitutions so a path with spaces works.

This project lives at "/Users/rc/Local Desktop/COWORK/Apps/AC app/ac-app" --
two spaces. The "Bundle React Native code and images" phase that Expo's prebuild
template generates ends with:

    /bin/sh `"$NODE_BINARY" --print "...sentry-xcode.sh"` `"$NODE_BINARY" --print "...react-native-xcode.sh"`

The backticks are UNQUOTED, so the resulting paths word-split at the space and
the build dies with:

    /bin/sh: /Users/rc/Local: No such file or directory
    Command PhaseScriptExecution failed with a nonzero exit code

`ios/` is gitignored and regenerated by `expo prebuild`, so a hand-edit there
does not survive. This script is tracked, is idempotent, and is run by
scripts/build_ios_local.sh before every local build -- so it self-heals after a
prebuild instead of silently reverting.

It touches ONLY the local Xcode project. EAS builds check out to a space-free
path and never hit this, so nothing about the shipped build changes.
"""
import os
import re
import sys

BASE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PBX = os.path.join(BASE, "ios", "FlyRegs.xcodeproj", "project.pbxproj")

# The pbxproj stores each script as ONE escaped string, so `"` appears as \" .
#
# Deliberately general: match ANY backtick command substitution, not just
# `"$NODE_BINARY" --print`. Fixing them one at a time meant three builds and
# three separate failures -- the RN bundle phase, then Sentry's debug-symbol
# upload (`${NODE_BINARY:-node} --print ...`), and every one of them is the same
# defect. Any unquoted substitution whose output is a path breaks on a path with
# spaces, so quote them all.
BACKTICK = re.compile(r"`([^`\n]+)`")


def main():
    if not os.path.exists(PBX):
        print(f"SKIP: no {PBX} (run `expo prebuild` first)")
        return 0
    src = open(PBX, encoding="utf-8").read()
    fixed, n = BACKTICK.subn(lambda m: '\\"$(' + m.group(1) + ')\\"', src)
    if n == 0:
        print("already quoted (or upstream fixed it) -- nothing to do")
        return 0
    open(PBX, "w", encoding="utf-8").write(fixed)
    print(f"quoted {n} unquoted command substitution(s) in the RN bundle phase")
    return 0


if __name__ == "__main__":
    sys.exit(main())
